name: Docker Image CI

on:
  push:
    branches: [ dev ]

# on:
#   release:
#     types: [ published ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Get the version
      run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD-HHmmss
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_USER }}/hubitat2prom:${{ steps.current-time.outputs.formattedTime  }}
        # tags: |
        #   ${{ secrets.DOCKER_USER }}/hubitat2prom:${{ env.TAG }}
        #   ${{ secrets.DOCKER_USER }}/hubitat2prom:latest
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USER }}/hubitat2prom